version: '3.8'
services:
  db:
    image: mysql:8
    container_name: movie-booking-db
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=movie_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:latest
    container_name: movie-booking-redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: movie-booking-app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/movie_db?characterEncoding=UTF-8&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_REDIS_HOST=redis
