server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: movie_user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: localhost
    port: 6379

jwt:
  secretKey: "abcdefghijklmnopqrstuvwxyz123456"  # 실제 운영 시 안전하게 보관

logging:
  level:
    org.hibernate.SQL: debug
